Lesson 04
wild-north/js_feb_2021 pull request #11
Opened 2021-03-17 19:00 UTC by GlebYelizov

Homework_lesson_04

2021-03-18 10:23 UTC, wild-north requested changes

2021-03-18 10:23 UTC, wild-north commented on Gleb_Yelizov/main.js
> +        paired.push(arr[i]);
not properly formatted, should have additional indent for this line

2021-03-18 10:23 UTC, wild-north commented on Gleb_Yelizov/main.js
> +        else continue;
if and else construction should never be used without curly brackets. You should have used here such a construction:
if () {
    ////
} else {
    ////
}

2021-03-18 10:23 UTC, wild-north commented on Gleb_Yelizov/main.js
> +    for (let j = (arr.length - 1); j >= 0; j--) {
brackets in `(arr.length - 1)` are redundant here

2021-03-18 10:23 UTC, wild-north commented on Gleb_Yelizov/main.js
> +            if (arr[j] % 2 !== 0) {
it is applicable to use here || (OR) operator instead of using nested if statements:

`if (arr[j] !== 0 || arr[j] % 2 !== 0) { ... }`

2021-03-18 10:23 UTC, wild-north commented on Gleb_Yelizov/main.js
> +function findIndex(array, elementToFind) {
Please, read the task carefully - the function must return an index or -1 and no arrays need to be returned.

2021-03-18 10:23 UTC, wild-north commented on Gleb_Yelizov/main.js
> +                    else {
no line breaks needed here.

2021-03-18 10:23 UTC, wild-north commented on Gleb_Yelizov/main.js
> +                feetNumbers.push(i);
instead of pushing in the array, you could use return construction, like:
(please note using a strict comparison here (`===`) instead of `==`.
`if (elementToFind === array[i]) {
     return array[i];
}`

2021-03-18 10:23 UTC, wild-north commented on Gleb_Yelizov/main.js
> +let array = [1, 2, 3, 8, 4, 5, 6, 7, 8, 9, 10];
why have you used a manually created array instead of created with the function createArray?
Doesn't `arr` fit here?

2021-03-18 10:23 UTC, wild-north commented on Gleb_Yelizov/main.js
> +document.write(`Indexes of found elements: ${findIndex(array, elementToFind)} <br \/>`);
you can pass needed arguments as literal, like `findIndex(array, 8)`

2021-03-18 18:28 UTC, GlebYelizov commented on Gleb_Yelizov/main.js
> +        paired.push(arr[i]);
Done

2021-03-18 18:28 UTC, GlebYelizov commented on Gleb_Yelizov/main.js
> +        paired.push(arr[i]);
Done

2021-03-18 18:28 UTC, GlebYelizov commented on Gleb_Yelizov/main.js
> +        else continue;
Done

2021-03-18 18:28 UTC, GlebYelizov commented on Gleb_Yelizov/main.js
> +    for (let j = (arr.length - 1); j >= 0; j--) {
removed

2021-03-18 18:29 UTC, GlebYelizov commented on Gleb_Yelizov/main.js
> +            if (arr[j] % 2 !== 0) {
I changed code using && and it works fine. Am I wrong?

2021-03-18 18:30 UTC, GlebYelizov commented on Gleb_Yelizov/main.js
> +function findIndex(array, elementToFind) {
ok

2021-03-18 18:30 UTC, GlebYelizov commented on Gleb_Yelizov/main.js
> +                    else {
ok

2021-03-18 18:32 UTC, GlebYelizov commented on Gleb_Yelizov/main.js
> +                feetNumbers.push(i);
I just wanted to predict several found numbers and thats why I used array. 
Changed to strict comparison.

2021-03-18 18:34 UTC, GlebYelizov commented on Gleb_Yelizov/main.js
> +let array = [1, 2, 3, 8, 4, 5, 6, 7, 8, 9, 10];
I have used manually created array to put few numbers to be found. 
arr fits too, why not? Changed to arr

2021-03-18 18:34 UTC, GlebYelizov commented on Gleb_Yelizov/main.js
> +document.write(`Indexes of found elements: ${findIndex(array, elementToFind)} <br \/>`);
done

2021-03-19 13:26 UTC, wild-north commented on Gleb_Yelizov/main.js
> +        if ((arr[i] % 2 == 0) && !(arr[i] == 0)) {
no need to move the `!` out from comparison expression, you could left if like that
```suggestion
        if ((arr[i] % 2 === 0) && arr[i] !== 0) {
```
also, please notice that I've changed `==` to `===` in the first expression

2021-03-19 13:26 UTC, wild-north commented on Gleb_Yelizov/main.js
> +function findIndex(arr, elementToFind) {
let's discuss this one at the lesson

2021-03-25 11:16 UTC, merged